# LENS COLOR
derigo_lens_color = {
    'Grey': [
        'Grey', 'Grey/GreenGrey/Green', 'Smoke', 'Smoke Gradient',
        'Smoke Gradient Smoke', 'Smoke/Mirror Silver', 'Smoke Gradient/Mirror Silver',
        'Smoke Gradient Beige', 'Smoke/Deg.Mirror Silver'
    ],
    'Green': [
        'Green', 'Green Gradient Green', 'Green Gradient', 'Smoke Multilayer Green',
        'Green/Mirror Red', 'Green/Deg.Mirror Silver', 'Green Gradient Brown'
    ],
    'Blue': [
        'Blue', 'Blue Gradient', 'Smoke/Mirror Blue', 'Blue Gradient Yellow',
        'Blue Gradient Smoke', 'Blue Gradient Blue', 'Blue/Mirror Blue',
        'Smoke Gradient/Mirror Blue', 'Smoke Gradient Blue', 'Blue/Mirror Silver'

    ],
    'Brown': [
        'Brown', 'Brown Gradient', 'Brown Gradient Brown', 'Brown Gradient Blue',
        'Brown Gradient Pink', 'Smoke/Mirror Bronze', 'Brown Mirror Bronze',
        'Brown/Mirror Violet',
    ],
    'Red': [
        'Red', 'Red Gradient', 'Red Mirror Silver'
    ],
    'Violet': [
        'Violet', 'Violet Gradient', 'Violet/Mirror Silver', 'Violet Gradient Pink',
        'Smoke Mirror Violet',
    ],
    'Pink': [
        'Pink', 'Pink/Multilayer White', 'Pink Gradient'
    ],
    'Yellow': [
        'Yellow Gradient/Mirror Gold', 'Yellow', 'Brown/Mirror Gold'
    ],
    'Orange': [
        'Orange', 'Violet Gradient Orange'
    ]
}

# FRAME COLOR
derigo_frame_color = {
    'Brown': [
        'Marrone/Senape Striato Lucido',
        'Marrone/Senape Striato Lucido',
        'Marrone Trasparente',
        'Marrone Striato Lucido',
        'Marrone Striato+ Glittery Lucido',
        'Marrone/Verde Striato Lucido',
        'Avana Marrone/Azzurro Lucido',
        'Avana Marrone/Beige Lucida',
        'Marrone Trasparente Opaco',
        'Marrone C/Parti Blu',
        'Light Brown',
        'Palladio Lucido C/Parti Marrone',
        'Marrone Melange Lucido',
        'Rutenio C/Parti Marrone',
        'Marrone/Avana Lucido',
        'Fantasia Marrone',
        'Bordeaux Sfumato Marrone Lucido',
        'Ocra/Marrone Striato Sfumato',
        'Avana Petrolio/Marrone Lucida',
        'Marrone Oliva Lucido',
        'Marrone C/Striature Viola',
        'Marrone/Rosa/Arancio Striato',
        'Marrone Striato+Verde',
        'Rosso/Blu/Marrone Lucido',
        'Avana Marrone',
        'Avana Marrone/Miele',
        'Marrone Sfumato Grigio',
        'Avana Senape Striata Marrone Lucido',
        'Marrone Trasparente Lucido',
        'Brown',
        'Brown, Grey',
        'Brown/Black',
        'Brown, Black',
        'Brown/Gold',
        'Gold, Brown',
        'Brown, Green',
        'Brown, Grey, Blue',
        'Brown, Olive',
        'Grey, Brown',
        'Brown, Gold',
        'Top Marrone+Grigio',
        'Marrone Striato+Cognac',
        'Blu+Marrone Lucido',
        'Marrone Striato+Blu',
        'Dark Brown',
        'Brown/Olive',
        'Marrone Pieno C/Parti Arancio Lucido'
    ],
    'Black': [
        "Oro Rose' Luc.C/Parti Nero Luc",
        'Nero Lucido',
        'Nero Opaco',
        "Oro Rose' Lucido C/Parti Nero Semilucido",
        'Nero Lucido Totale',
        'Bachelite C/Parti Nero Opaco',
        'Nero Marmorizzato',
        'Nero Opaco C/Parti Nero Lucido',
        "Oro Rose' Lucido C/Parti Nero Lucido",
        "Nero Semilucido C/Parti Oro Rose'",
        'Oro Rose+Nero Opaco',
        'Avana Verde+Nero Lucido',
        'Nero Semilucido Totale',
        'Nero Sfumato Grigio Opaco',
        'Multilayer Nero',
        'Palladio C/Parti Nero Lucido',
        'Nero Lucido C/Parti Rosso Semilucido',
        'Top Nero+Arancio',
        'Top Nero Est.+Blu Int. Lucido',
        'Nero+Avana',
        'Top Nero/Cristallo',
        'Palladio Lucido C/Parti Nero Semilucido',
        'Black',
        'Grey / Black',
        'Gold / Black',
        'Black Mat',
        'Black, Silver',
        'Gold, Black',
        'Black Gold',
        'Black.',
        'Palladium, Black',
        'Black...',
        'Copper, Black',
        'Black, Yellow',
        'Black, Grey',
        'Red, Black',
        'Dark Grey, Black',
        'Black / Gold',
        'Black, Grey, Red',
        'Black, Black',
        'Grey, Black',
        'Black, Red',
        'Blue, Black',
        'Black, Olive',
        'Black, Palladium',
        'Black, Green, Red',
        'Grey, Blue, Black',
        'Titanium, Black',
        'Olive/Black',
        'Light Gold, Black',
        'Light Blue, Black',
        'Grey Metal, Black',
        'Black, Green',
        'Black, Palladium, Red',
        'Black, Blue',
        'Black / Dark Blue',
        'Palladium / Black',
        'Nero Sabbiato/Opaco',
        'Nero+ Cristallo',
        'Oro Nero Lucido',
        'Bachelite Lucida C/Parti Nero Lucido',
        'Nero Semilucido C/Parti Rosso',
        'Black/Black',
        'Gold/Black',
        'Black/Grey',
        'Grey/Black/Blue',
        'Dark Grey/Black',
        'Black/Red',
        'Black/Gold'
    ],
    'Grey': [
        'Rutenio Lucido Totale',
        'Rutenio Lucido Totale',
        'Palladio Lucido Totale',
        'Grigio Opalino Opaco',
        'Grigio Trasparente',
        'Grigio Trasparente Lucido',
        'Grigio Scuro Opaco',
        'Oro Grigio Lucido',
        "Palladio Lucido C/Parti Oro Rose'",
        'Rutenio Lucido Tot.C/Parti Sabbiate/Opac',
        'Grigio',
        'Grigio Scuro Perlato Opaco',
        'Grigio C/Parti Blu',
        'Rutenio Opaco O Sabbiato Totale',
        'Rutenio Opaco C/Parti Colorate',
        'Grigio Scuro Trasparente Lucido',
        'Palladio Lucido C/Parti Blu Opaco',
        'Blu/Grigio Striato',
        'Grigio Pieno',
        'Grigio Opaco',
        'Azzurro/Grigio',
        'Grigio Sabbia C/Parti Rosso',
        'Rutenio Lucido Totale C/Parti Colorate',
        'Palladio Lucido C/Parti Blu',
        'Rutenio Lucido Totale C/Parti Sabbiate',
        'Grigio Trasparente Opaco',
        'Grigio Sfumato Blu Lucido',
        'Grigio Asfalto Opaco',
        'Grigio/Blu Pieno Lucido',
        'Palladio Lucido Con Parti Blu',
        'Palladio Lucido C/Parti Verde',
        'Palladio Lucido C/Parti Sabbiate E/O Opa',
        'Top Grigio Scuro+Grigio',
        'Grigio Scuro',
        'Avana Kaki Grigio/Verde/Giallo',
        'Rosso+Grigio',
        'Avana Azzurro Striato Grigio Lucido',
        'Grigio Pieno Opaco',
        'Top Grigio+Cristallo',
        "Oro Rose' Lucido C/Parti Palladio Lucido",
        'Rutenio Satinato Lucido Totale',
        'Palladio Lucido C/Parti Viola',
        'Palladio Satinato Lucido C/Parti Colorat',
        'Grey Mat',
        'Dark Grey, Olive',
        'Dark Grey',
        'Grey Blue',
        'Dark Grey, Blue, Green',
        'Palladium, Grey',
        'Grey',
        'Dark Grey, Blue',
        'Dark Grey, Red',
        'Olive, Dark Grey',
        'Grey, Blue',
        'Palladium, Grey, Blue',
        'Blue, Grey',
        'Grey, Gold',
        'Dark Grey, Dark Blue',
        'Grey, Red',
        'Gold, Grey',
        'Gold, Grey Green, Red',
        'Palladium, Blue Grey',
        'Blue, Dark Grey',
        'Crystal, Grey',
        'Grey, Grey',
        'Grey/Blue',
        'Dark Grey, Orange',
        'Clear, Grey',
        'Schwarz, Grey',
        'Blue, Grey, Red',
        'Gold / Grey',
        'Dark Grey, Green',
        'Quadri Grigio Lucido',
        'Grigio Scuro Trasp.Luc.',
        'Grigio Scuro Sfumato Grigio Chiaro Lucid',
        'Blu/Grigio Sfumato Azzurro Lucido',
        'Blue/Grey',
        'Dark Grey/Olive',
        'Grey/Grey Blue',
        'Grey Green',
        'Dark Grey/Grey',
        'Light Grey/Grey',
        'Palladium/Grey',
        'Grey/Olive',
        'Dark Grey/Green',
        'Grigio C/Vernice Gommata'
    ],
    'Blue': [
        "Oro Rose' Lucido Totale",
        "Oro Rose' Lucido C/Parti Sabbiate/Satin/",
        "Oro Rose' Lucido",
        'Oro Endura Lucido Con Parti Sabbiate O O',
        'Oro Chiaro Lucido',
        'Oro Ramato Lucido',
        'Oro Rosso Lucido Totale',
        "Oro Rose' Opaco C/Parti Lucide",
        'Viola+Giallo',
        'Oro Ramato Lucido C/Parti Colorate',
        'Oro Rosso Lucido C/Parti Colorate',
        "Oro Rose' C/Parti Avorio Lucido",
        "Oro Rose' Con Cartina Beige",
        'Gold',
        'Light Gold',
        'Yellow Gold',
        'Light Gold.',
        'Gold, Olive',
        'Shiny Gold',
        'Light Gold Mat'
    ],
    'Green': [
        'Verde Trasparente Lucido',
        'Verde Pieno Lucido',
        'Top Avana+Verde Lucido',
        'Verde Scuro Sfumato Verde Chiaro Lucido',
        'Verde Opaco',
        'Verde Scuro Lucido',
        'Multilayer Verde',
        'Verde Striato+Corno Verde',
        'Verde Scuro Semilucido',
        'Striato Verde Militare Lucido',
        'Verde/Azzurro Lucido',
        'Verde Trasparente',
        'Top Verde Bottiglia+Cristallo Lucido',
        'Verde Striato Lucido',
        'Green',
        'Olive',
        'Verde Kaki Lucido',
        'Verde Opalino Lucido',
        'Verde Scuro+Chiaro Lucido',
        'Petrol',
        'Verde Acqua Lucido'
    ],
    'Red': [
        'Rosso Marmorizzato',
        'Bordeaux Pieno',
        'Rosso Bordeaux Trasparente Lucido',
        'Rosso Opaco',
        'Bachelite C/Parti Rosso',
        'Bordeaux Pieno Lucido',
        'Top Bordeaux+Viola',
        'Rosso Ciliegia Pieno Lucido',
        'Rosso Pieno Opaco',
        'Rosso Pieno Lucido',
        'Rosso Trasparente Lucido',
        'Bordeaux Scuro Trasparente Lucido',
        'Rosso Trasp.Opaco',
        'Bordeaux Scuro Trasparente Opaco',
        'Bordeaux',
        'Bordeaux Lucido',
        'Red',
        'Ruthenium / Red',
        'Corno Viola+Rigato Bordeaux'
    ],
    'Violet': ['Fuxia Pieno Lucido', 'Avana+Fuxia Lucido', 'Ciclamino Trasparente Lucido'],
    'Pink': ['Rosa Trasparente Lucido', 'Viola Sfumato Rosa Lucido', 'Rosa Chiaro Trasparente Lucido'],
    'Orange': ['Arancio Trasparente Lucido', 'Avana Arancio Lucido', 'Pesca Trasparente Lucido'],
    'White': ['Bianco Neve Lucido', 'Bianco Neve Opaco'],
    'Miscellaneous': [
        'Bachelite Opaca',
        'Avana Scura Opaca',
        'Avana Scura Lucido',
        'Ocra Trasparente Lucido',
        'Bachelite Lucida Totale',
        'Bachelite Lucida Totale/Con Variante',
        'Avana Scura',
        'Avana Scura Lucida',
        'Beige Trasparente',
        'Vinaccia Trasparente Lucido',
        'Avorio Pieno Lucido',
        'Avana Gialla Lucida',
        'Viola Pieno',
        'Viola Trasparente Lucido',
        'Marron Chiaro Trasparente Lucido',
        'Opa',
        'Beige Trasparente Lucido',
        'Avana Media Lucida',
        'Avana Bianca/Nera Lucida',
        'Avana Vintage Lucida',
        'Multilayer Avana',
        'Tortora Lucido',
        'Avana Nera Grigia',
        'Marron Lucido Totale',
        'Marron Trasparente',
        'Bachelite Lucida C/Parti Sabbiate E/O Op',
        'Avana Classica Lucida',
        'Cammello Tan Lucido',
        'Avana Chiara Lucida',
        'Cammello Tan Lucido C/Parti Colorate',
        'Marron Semilucido C/P.Ti Lucide',
        'Avana Lucida',
        'Cristallo Lucido',
        'Avana',
        'Avana Gialla/Viola Lucida',
        'Prugna Trasparente',
        'Avana Classica Opaca',
        '7Rrm',
        'Azzurro Carta Di Zucchero Opaco',
        '7Adm',
        'Azzurro Trasparente',
        'Fantasia Viola',
        'Viola Scuro Trasparente Lucido',
        'Bronzo Satinato Lucido',
        'Avana Maculata Gialla Con Marron Lucido',
        'Bordeux Pieno',
        'Porpora Lucida',
        'Avana Cipria Lucida',
        'Palladium',
        'Bronce',
        'Silver',
        'Titanium.',
        'Copper',
        'Titanium..',
        'Dark Gun',
        'Palladium.',
        'Titanium',
        'Darkgrey',
        'Gun',
        'A10',
        'A15',
        'A20',
        'A25',
        'A30',
        'B10',
        'B15',
        'B20',
        'B25',
        'B30',
        'C10',
        'C15',
        'C20',
        'C25',
        'C30',
        'Silver Mat',
        'Satin Gun',
        'Gun.',
        'Titanium Mat',
        'Alluminium',
        'Tortora Trasparente',
        'Avana Quadri',
        'Viola Opalino Lucido',
        'Malva Trasparente Lucido',
        'Top Viola/Azzurro Trasparente',
        'Azzurro Semiopaco',
        'Prugna Pieno Lucido',
        'A173',
        'T651',
        'Viola Pieno Lucido C/Parti Colorate'
    ]
}

# LENS TECHNOLOGY
derigo_lens_technology = {
    'Polarized': ['Polarized', 'Polarizzante+Antiriflesso'],
    'Photochromic': ['Fotocromatico+Antiriflesso', 'Fotocromatico'],
    'Standard': ['Standard']
}

# FRAME MATERIAL
derigo_frame_material = {
    'Plastic': ['Acetato', 'Iniettato'],
    'Metal': ['Metallo']
}