# FRAME COLOR
safilo_frame_color = {
    'Black': [
        'Gold Black_',
        'Black Gold',
        'Black',
        'Black Horn',
        'Ruthenium Black',
        'Black Silver',
        'Black Grey Horn',
        'Black Havana Blue',
        'Black Havana',
        'Black Ruthenium',
        'Matte Black Gold',
        'Light Gold Black Cream Horn',
        'Matte Black',
        'Matte Black Silver',
        'Black Beige',
        'Black Palladium',
        'Dark Ruthenium Black',
        'Ruthenium Matte Black',
        'Black Havana Gold',
        'Grey Black',
        'Black White',
        'Black Yellow',
        'Black Grey',
        'Havana Black',
        'Black Orange',
        'Black Azure',
        'Black Crystal',
        'Gold Shiny Black Matte Black',
        'Black Multicolor',
        'Palladium Black',
        'Matte Black Blue',
        'Crystal Black',
        'Black Blue',
        'Matte Black Pink',
        'Matte Black Yellow',
        'Yellow Fluo Black',
        'Semimatte Black',
        'Black Lavender',
        'Matte Black 1',
        'Shiny Black',
        'Shiny Black Rose Gold',
        'Rubber Black',
        'Matte Black Green',
        'Matte Black Red',
        'Matte Black Black Pink',
        'Silver Black',
        'Matte Black Violet',
        'Black Green',
        'Black Red Gold',
        'Black Rubber Fluorescent Orange',
        'Black Turquoise',
        'Black Red',
        'Blackcrystal Blackwhite Red',
        'Yellow Black',
        'Black Shaded Brown',
        'Blackcrystal Blackwhiteblue',
        'Black Opal Brown',
        'Black Crystal Black Crystal White',
        'Black Crystal Black White Red',
        'Black Crystal Black White Blue',
        'Striped Black',
        'Black Pink',
        'Black Brown',
        'Matte Black Dark Ruthenium Crystal Red',
        'Havana Matte Black',
        'Black Crystal Red',
        'Black Crystal Yellow',
        'Green Black',
        'Orange Black',
        'Orange Fluo Black',
        'Black Aluminum Cactus Green',
        'Glitter Black',
        'Black Blue Havana',
        'Black Copper Gold',
        'Black Striped Brown',
        'Matte Gold Black',
        'Matte Black Ruthenium',
        'Black Fuchsia',
        'Bordeaux Black',
        'Matte Black Semimatte Dark Ruthenium',
        'Matte Black Black',
        'Blue Black', 'Blck',
        'Black Ruthenium Black',
        'Havana Red Shiny Black',
        'Black Matte Black',
        'Black Gold Copper',
        'Dark Grey Black Spotted Grey',
        'Havana Black Crystal',
        'Black Havana Grey',
        'Matte Black Petrol',
        'Matte Blue Black',
        'Black Shiny Light Ruthenium Dark Light Grey',
        'Matte Black Dark Ruthenium',
        'Matte Black Havana',
        'Dark Grey Black',
        'Gold Striped Black',
        'Black Dark Ruthenium',
        'Matte Black Grey',
        'Matte Burgundy Black',
        'Matte Black Orange',
        'Brown Black',
        'Pattern Black White',
        'White Black',
        'Black Aqua',
        'Pink Black',
        'Black Burgundy',
        'Matte Black Gold Black',
        'Olive Black',
        'Matte Ruthenium Black',
        'Gold Pattern Black',
        'Cherry Pattern Black',
        'Havana Brown Black',
        'Matte Dark Ruthenium Black',
        'Matte Black Cornflower Blue Matte White Dark Blue',
        'Black Dark Grey',
        'Matte Black Palladium',
        'Matte Black Horn',
        'Black Khaki',
        'Black Semimatte Dark Ruthenium',
        'Shiny Matte Black Black Crystal',
        'Black Crystal_',
        'Nude Black',
        'Black Nude',
        'Fuchsia Black',
        'Pattern Black Grey',
        'Black Pattern Grey',
        'Black Pattern White',
        'Black White Havana',
        'Black Pattern Brown',
        'Black_',
        'Matt Black1',
        'Matte Black Gold Copper'
    ],
    'Grey': [
        'Grey',
        'Grey Gold',
        'Grey Horn',
        'Gold Grey',
        'Grey Dark Ruthenium',
        'Ruthenium Grey Horn',
        'Green Grey',
        'Havana Grey',
        'Palladium Havana Grey Palladium',
        'Grey Burgundy',
        'Grey Yellow',
        'Blue Grey',
        'Grey Green',
        'Beige Grey',
        'Grey Red',
        'Grey Blue',
        'Matte Grey',
        'Grey Shaded Honey',
        'Grey Orange',
        'Shaded Grey',
        'Grey Metallic Anthracite',
        'Grey Crystal',
        'Striped Grey',
        'Brown Striped Grey',
        'Ruthenium Grey',
        'Grey Ruthenium',
        'Grey Silver',
        'Grey Horn Gold',
        'Horn Grey',
        'Shaded Grey Texture Transparent Gre',
        'Silver Grey',
        'Matte Light Gold Grey',
        'Matte Blue Grey',
        'Blue Horn Grey',
        'Transparent Blue Striped Shiny Grey',
        'Matte Grey Orange',
        'Violet Grey',
        'Dark Grey',
        'Shaded Dark Blue Texture Grey Trans',
        'Grey Beige',
        'White Grey',
        'Matte Grey Blue',
        'Matte Grey Green',
        'Grey Shaded Crystal',
        'Metalized Grey',
        'Matte Grey Ruthenium',
        'Grey Pink',
        'Matte Grey Brown',
        'Grey Yellow Fluo',
        'Crystal Grey',
        'Palladium Grey',
        'Shaded Grey Pink',
        'Blue Shaded Grey',
        'Brown Shaded Grey',
        'Silver', 'Platinum', 'Ruthenium', 'Dark Ruthenium', 'Smoke Silver'
    ],
    'Blue': [
        'Blue',
        'Havana Azure',
        'Blue Azure',
        'Orange Blue',
        'Blue Ruthenium',
        'Havana Blue',
        'Palladium Azure',
        'Azure Ruthenium',
        'Azure Pearled',
        'Gold Blue',
        'Matte Blue',
        'Blue Yellow',
        'Azure',
        'Transparent Blue Transparent Bluette',
        'Azure Turquoise',
        'Blue Green',
        'Dark Ruthenium Blue',
        'Violet Shaded Azure Violet',
        'Blue Havana',
        'Blue Havana Gold',
        'Blue Gold',
        'Blue Red Opal White Opal Light Blue',
        'Ruthenium Blue',
        'Matte Dark Blue',
        'Matte Blue Blue',
        'Blue White',
        'Blue Shaded',
        'Blue Orange',
        'Blue Green Fluo',
        'Transparent Blue Transparent Cornflower Blue',
        'Blue Beige',
        'Semimatte Blue',
        'Striped Blue',
        'Matte Ruthenium Blue',
        'Blue Silver',
        'Blue Horn',
        'Brown Blue',
        'Azure Havana',
        'Green Azure',
        'Matte Blue Green',
        'Matte Blue Ruthenium',
        'Gold Matte Azure', 'Turquoise'
                            'Blue Aqua Striped Aqua',
        'Azure Rose Gold',
        'Blue Stripes Blue',
        'Semimattblue Violet Azure',
        'Matt Blue Azure',
        'Blue Matte Palladium',
        'Matte Blue Horn',
        'Matte Dark Ruthenium Blue',
        'Striped Blue Palladium',
        'Matte Blue Gold',
        'Blue Nude',
        'Blue Antique Blue',
        'Blue Pattern',
        'Blue Burgundy',
        'Matte Blue Red',
        'Blue Dark Ruthenium',
        'Blue Red',
        'Metalized Blue',
        'Marble Blue',
        'Ruthenium Blue Ruthenium',
        'Matte Blue Dark Ruthenium',
        'Matte Blue Palladium',
        'Blue Pattern White',
        'Blue Glitter',
        'Matte Blue Burgundy',
        'Crystal Blue',
        'Blue Crystal',
        'Brown Azure Havana',
        'Blue Red White Red White Blue',
        'Matt Blue Burgundy',
        'Blue White Red White',
        'Brown Blue Havana'
    ],
    'Green': [
        'Green',
        'Ruthenium Green',
        'Gold Green',
        'Matte Green',
        'Havana Green',
        'Matt Green Havana',
        'Green Gold',
        'Military Green',
        'Crystal Green',
        'Green Pink',
        'Green Ruthenium',
        'Green Horn',
        'Matte Palladium Green',
        'Green Yellow',
        'Green Lilac',
        'Matte Green Army Green',
        'Green Crystal', 'Olive'
    ],
    'Brown': [
        'Gold Havana',
        'Brown Striped Havana',
        'Honey Brown Cream Horn',
        'Dark Havana',
        'Havana Silver',
        'Ruthenium Havana',
        'Havana Horn Camel',
        'Red Havana',
        'Brown Horn',
        'Havana',
        'Striped Brown',
        'Dark Ruthenium Havana',
        'Brown Havana',
        'Havana Honey',
        'Dark Havana Brown',
        'Gold Cream Brown Horn',
        'Havana Gold',
        'Brown Havana Striped Beige',
        'Dark Havana Gold',
        'Brown Horn Ruthenium',
        'Brown',
        'Ruthenium Brown',
        'Havana Crystal',
        'Havana Ruthenium',
        'Dark Ruthenium Brown',
        'Red Havana Dark Ruthenium',
        'Matte Brown Dark Ruthenium',
        'Violet Brown',
        'Havana Brown Glitter Gold',
        'Havana 2',
        'Havana Yellow',
        'Brown Gold',
        'Gold Brown',
        'Havana Cherry',
        'Havana Teal',
        'Havana Beige',
        'Havana Violet',
        'Havana Brown',
        'Medium Havana',
        'Matte Havana',
        'White Brown',
        'Havana Orange',
        'Light Gold Havana',
        'Dark Havana Light Gold',
        'Light Havana',
        'Matte Brown',
        'Brown Shaded Beige',
        'Brown Stripped Brown',
        'Havana Red',
        'Havana Burgundy',
        'Antique Brass Havana',
        'Havana Pink',
        'Burgundy Havana',
        'Gold Brown Havana',
        'Semimatte Brown',
        'Matt Striped Brown',
        'Yellow Havana',
        'Matte Brown Matte Ruthenium Matte Brown',
        'Matte Ruthenium Havana',
        'Gold Striped Brown',
        'Silver Havana',
        'Matte Light Brown Matte Light Gold Dove',
        'Brown Horn Gold',
        'Striped Brown Ruthenium',
        'Havana Metalized Brown',
        'Havana Burgundy Pearled Purple',
        'Horn Brown',
        'Havana Peach',
        'Lilac Havana',
        'Palladium Havana',
        'Dark Havana Glitter Gold',
        'Brown Crystal',
        'Pink Havana',
        'Yellow Havana Brown',
        'Gold Brown Horn',
        'Pink Striped Brown',
        'Havana Dark Ruthenium',
        'Beige Brown',
        'Cherry Havana',
        'Havana Turquoise',
        'Matte Dark Ruthenium Havana',
        'Brown Palladium',
        'Gold Honey Havana',
        'Nude Brown',
        'Matte Brown Gold',
        'Matte Dark Ruthenium Brown',
        'Beige Havana',
        'Peach Havana',
        'Brown Havana Matte Ruthenium',
        'Brown Brown Havana',
        'Crystal Havana',
        'Matte Brown Ruthenium',
        'Peach Dark Brown',
        'Violet Havana',
        'White Havana',
        'Olive Havana',
        'Matte Brown Havana',
        'Pattern Havana',
        'Brown Marble',
        'Brown Nude',
        'Nude Pink Havana'
    ],
    'Orange': [
        'Orange Beige',
        'Orange',
        'White Orange',
        'Matte Orange',
        'Beige Orange',
        'Matte Dark Ruthenium Orange',
        'Orange Ruthenium',
        'Gold Orange'
    ],
    'Pink': [
        'Red Pink', 'Nude',
        'Pink Peach',
        'Pink',
        'Pearld Pink',
        'Pink Violet',
        'Gold Pink',
        'Pink Gold',
        'Pink Silver',
        'Burgundy Pink',
        'Pink Beige',
        'Matte Pink',
        'Pink Red',
        'Pink Lilac',
        'Pink Burgundy',
        'Pink Horn',
        'Light Pink',
        'Pink Fuchsia',
        'Pink Crystal'
    ],
    'Yellow': [
        'Gold',
        'Light Gold Beige Horn',
        'Gold Beige Horn',
        'Gold Peach',
        'Yellow Gold',
        'Gold Copper',
        'Gold Teal',
        'Yellow',
        'Gold Burgundy',
        'Gold 1',
        'Copper Gold',
        'Gold Crystal',
        'Light Gold',
        'Gold Burgundy Gold',
        'Burgundy Copper Gold',
        'Semimatte Gold',
        'Gold Violet Gold',
        'Crystal Yellow',
        'Honey Gold',
        'Rose Gold',
        'Matte Gold',
        'Red Gold',
        'Rose Gold Crystal',
        'White Yellow',
        'Gold Ivory',
        'Gold Mud',
        'Gold Nude',
        'Gold Red',
        'Light Gold Light Peach',
        'Lilac Gold Copper',
        'Cherry Gold',
        'Crystal Gold',
        'Violet Gold',
        'Copper Gold Nude',
        'Light Gold Lilac',
        'Gold Striped Red',
        'Yellow Horn',
        'Striped Yellow',
        'Striped Beige Gold',
        'Matt Yellow',
        'Gold Violet',
        'Palladium Yellow',
        'Matte Aqua Gold',
        'Matte Ivory Gold',
        'Matte Rose Gold',
        'Gold Lilac',
        'Gold White',
        'Gold Beige',
        'Gold Horn',
        'Gold Ochre',
        'White Gold',
        'Gold Silver',
        'Beige Gold',
        'Lilac Gold',
        'Matte Burgundy Gold',
        'Matte Light Gold',
        'White Copper Gold',
        'Ivory Gold Copper',
        'Opal Red Red Glitter Gold',
        'Gold Yellow'
    ],
    'Red': [
        'Red',
        'Matte Red',
        'Teal Red',
        'Red Crystal',
        'Red Violet',
        'Beige Red',
        'Burgundy Pattern Red',
        'Red Glitter',
        'Burgundy Red',
        'Red Red Horn', 'Opal Burgundy'
    ],
    'Violet': [
        'Violet Lilac',
        'Violet',
        'Fuchsia',
        'Palladium Violet',
        'Violet White',
        'Burgundy Fuchsia',
        'Violet Beige',
        'Matte Violet Lilac',
        'Nude Violet',
        'Matte Violet',
        'Violet Palladium',
        'Fuchsia Palladium', 'Purple'
    ],
    'White': [
        'White', 'Ivory', 'Palladium', 'Nude White', 'Crystal',
        'Matte     Ivory'
    ],
    'Miscellaneous': [
        'Mud',
        'Ochre',
        'Peach',
        'Beige',
        'Copper',
        'Burgundy',
        'Plum',
        'Crystal',
        'Lilac',
        'Cherry',
        'Petrol',
        'Semimatte Dark Ruthenium',
        'Salmon',
        'Aqua',
        'Lime',
        'Gun',
        'Dark Gun',
        'Gunmetal',
        'Ruthenium Khaki',
        'Champagne',
        'Crystal Rubber Purple',
        'Matte Dark Ruthenium',
        'Burgundy Shaded',
        'White Crystal',
        'Matte Ruthenium',
        'Cyclamen',
        'Semimatte Bronze',
        'Matte Bronze',
        'Teal',
        'Beige Crystal',
        'Sage',
        'Striped Olive',
        'Beige Horn',
        'Palladium Burgundy',
        'Burgundy Ochre',
        'Khaki Beige',
        'Silver',
        'Peach Palladium',
        'Striped Burgundy',
        'Matt Aqua',
        'Matte Burgundy',
        'Mattkhaki Burgundy',
        'Matte Lime',
        'Horn',
        'Brick',
        'Matte White',
        'Matte Dark Ruthenium Horn',
        'Mauve',
        'Cherry Palladium',
        'Horn Beige',
        'Burgundy Palladium',
        'Khaki',
        'Shaded Burgundy',
        'Matte Burgundy Palladium',
        'Palladium Horn',
        'Matte Palladium',
        'Crystal Beige',
        'Nude Beige',
        'Matte Silver',
        'Matte Teal',
        'Matte Crystal',
        'Matte Burgundy Ruthenium',
        'Multicolor'
    ]
}

# ============================================================================================
# LENS COLOR
safilo_lens_color = {
    'Black': ['Black Brown Green Antireflex'],
    'Grey': [
        'Grey',
        'Dark Grey Shaded',
        'Grey Polarized',
        'Grey Shaded Gold Mirror',
        'Grey Bronze Mirror',
        'Grey Mirrorshade Silver',
        'Grey Shaded Polarized',
        'Grey Azure',
        'Grey Green',
        'Silver',
        'Grey Silver Flash Polarized',
        'Grey Gradient Brown',
        'Grey Blue Mirror Polarized',
        'Grey Gold Mirror Polarized',
        'Grey Rose Gold Mirror Multilayer',
        'Grey Pink Mirror Polarized',
        'Grey Multilayer Deg',
        'Grey Antireflex',
        'Dk Grey Ochre Doubleshade',
        'Grey Shaded',
        'Grey Flash Silver Polarized',
        'Grey Multilayer Green Polarized'
    ],
    'Green': [
        'Green Shaded',
        'Green',
        'Green Lightgreen Antireflex',
        'Green Mirror',
        'Green Polarized',
        'Green Shaded Polarized',
        'Green Shaded Gold Mirror Antirefex',
        'Green Shaded Flash Gun Metal',
    ],
    'Brown': [
        'Brown Antireflex',
        'Brown',
        'Brown Shaded',
        'Brown Sm Silver',
        'Brown Shaded Polarized',
        'Brown Polarized',
        'Brown Pink Shaded',
        'Brown Polar Doubleshade',
        'Brown Mirrorshade Silver'
    ],
    'Orange': ['Orange', 'Orange Flash Multilayer'],
    'Pink': ['Gradient Pink', 'Pink', 'Pink Polarized', 'Pink Multilayer', 'Pink Mirror'],
    'Yellow': ['Yellow Photocromatic',
               'Gold Mirror',
               'Rose Gold Multilayer Polarized',
               'Yellow Mirror',
               'Multilayer Yellow'],
    'Red': [
        'Red',
        'Red Mirror Pz',
        'Red Multilaser',
        'Red Flash',
        'Red Multilayer Oleophobic Hd'
    ],
    'Vioelt': [
        'Violet Polarized',
        'Violet Shaded Polarized',
        'Violet Mirror',
        'Violet Mirror Polarized'
    ],
    'Miscellaneous': [
        'Purple Polarized',
        'Silver Mirror',
        'Burgundy',
        'Platinum Polarized',
        'Bronze Polarized',
        'Burgundy Shaded Polarized',
        'Purple Gradient Polarized',
        'Copper Polarized',
        'Blu Sky Mirror'
    ]
}

# ===============================================================================================
# FRAME SHAPE
safilo_frame_shape = {
    'Round': ['Round', 'Oval', 'Round Geometrical', 'Phantos'],
    'Square': ['Square', 'Square Flat Top', 'Square Double Bridge', 'Square Geometrical'],
    'Rectangular': [
        'Rectangular', 'Rectangular Geometrical', 'Rectangular Flat Top', 'Rectangular Browline'
    ],
    'Aviator': ['Aviator', 'Pilot', 'Navigator'],
    'Cat Eye': ['Cat Eye', 'Cat Eye / Butterfly'],
    'Butterfly': ['Butterfly', 'Butterfly Geometrical', ''],
    'Google': ['Mask', 'Goggle']
}

# FRAME MATERIAL
safilo_frame_material = {
    'Metal': ['Metal', 'Stainless Steel', 'Alluminium', 'Stainless Steel (Ss)', 'Metal (Me)'],
    'Plastic': ['Plastic', 'Acetate', 'Polyamide In-Gril.', 'Rubber', 'Rubber (Rb)'
                'Light Acetate', 'Light Acetate (La)'],
    'Bio': ['Eco Polyamide', 'Eco Co-Polyester', 'Eco Acetate',
            'Eco Polyamide (Ep)', 'Eco Acetate (Ea)', 'Eco Polycarbonate', 'Eco Stainless Steel'],
    'Titanium': ['Titanium', 'Beta-Titanium', 'Titanium (Ti)']
}

# GENDER
safilo_gender = {
    'Man': ['Man', 'Men', 'Boys & Teens 11-15', 'Boys &Amp; Teens 11-15'],
    'Woman': ['Woman', 'Women', 'Girls &Amp; Teens 11-15'],
    'Unisex': ['Unisex', 'Unisex Adults', 'Unisex Teens 11-15'],
    'Kids': ['Junior (7-10)', 'Young Kids (4-6)', 'Kids & Teens']
}