# LENS COLOR
lux_lens_colors = {
    "Black": [
        "Grey-Black", "Light Azure Mirr Gradient Black", "Light Grey Mirror Black",
        "Light Grey Gradient Black", "Prizm Black Polarized", "Prizm Black",
        "Prizm Snow Black Iridium", "Prizm Road Black", "Clear to Black Iridium Photochromic",
        "Black Iridium Polarized", "Black Iridium", "G40 Black Gradient", "Polarized Black",
        "Polar Black", "Black"
    ],

    "Grey": [
        "Grey Silver/Gold Graffiti", "Violet Gradient Dark Grey", "Light Grey Mirror Silver 80",
        "Dark Grey", "Polar Grey", "Grey", "Prizm Tungsten Polarized", "Prizm Grey Polarized",
        "Prizm Grey", "Prizm Tungsten", "Prizm Grey Gradient", "Grey Polarized", "Warm Grey",
        "Grey Gradient Polarized", "Grey Gradient", "Grey Photocromic", "Light Brown Gradient Light Grey",
        "Polarized Grey", "Photo Grey", "Polar Gray Gradient", "Polar Dark Grey", "Brown Gradient Grey",
        "Clear Gradient Grey", "Gray Gradient", "Polarized Dark Grey", "Light Grey Mirror Silver",
        "Photo Grey Blue Light Filter", "Polar Grey Gradient", "Pink Gradient Grey", "Brown Mirror Internal Grey",
        "Gradient Grey", "Blue/Grey", "Light Grey", "Brown/Grey", "Grey Mirror Silver",
        "Light Grey Gradient Dark Grey", "Silver"
    ],

    "Red": [
        "Prizm Ruby Polarized", "Prizm Ruby", "Positive Red Iridium", "Red Mirror Silver Internal",
        "Pink Gradient Red", "Red", "Clear Gradient Red", "Red Mirror", "Prizm Snow Torch", "Fire Iridium"
    ],

    "Yellow": [
        "Brown Mirror Gold", "Prizm Rose Gold Polarized", "Prizm Rose Gold", "Yellow",
        "Yellow Orange", "Gold Mirror", "Gold"
    ],

    "Pink": [
        "Clear Gradient Pink", "Pink", "Pink Photochromic", "Photo Pink To Dark Purple",
        "Corallo Sfumato", "Dark Pink", "Photo Pink To Purple", "Pink & Brown Gradient",
        "Pink Gradient Brown", "Light Purple Brown"
    ],

    "Blue": [
        "Dark Blue", "Prizm Sapphire Polarized", "Prizm Sapphire", "Prizm Snow Sapphire",
        "Sapphire Iridium", "Clear Blue Light Filter", "Light Violet Gradient Blue", "Blue",
        "Photo Clear To Blue", "Clear Blue", "Clear Gradient Light Blue", "Blue Mirror Silver 80",
        "Dark Blue Classic", "Blue Mirror", "Blue Gradient", "Deep", "Prizm Snow Sapphire Iridium"
    ],

    "Green": [
        "Polarized Green", "Prizm Jade", "Prizm Road Jade", "Prizm Snow Jade", "Prizm Jade Polarized",
        "Polar Green", "Dark Green", "Green Mirror Internal Silver", "Green Photochromatic",
        "G-15 Green", "Polarized Green Flash", "Green Gradient", "Green/Brown", "Prizm Shallow Water Polarized",
        "Green"
    ],

    "Brown": [
        "Vr50 Brown Gradient", "Brown", "Prizm Bronze", "Brown Mirror Gold", "Prizm Rose Gold Polarized",
        "Prizm Rose Gold", "Yellow", "Yellow Orange", "Gold Mirror", "Gold"
    ],

    "Clear": ["Clear"],

    "Violet": [
        "Prizm Violet", "Prizm Daily Polarized", "Prizm Dark Golf", "Prizm Road", "Prizm 24K",
        "Prizm Field", "Prizm 24K Polarized", "Prizm Trail Torch", "Fire Iridium", "Prizm Golf",
        "Chrome Iridium", "Prizm Tr22", "Violet", "Purple", "24K Iridium Polarized", "24K"
    ],

    "Orange": [
        "Orange Flash", "Dark Orange", "Orange", "Mirror Orange", "Orange Gradient Violet",
        "Orange Mirror", "Light Orange Mirror Internal Silver", "Orange Mirror Internal Silver",
        "Orange Mirror Gradient Silver"
    ],

    "Miscellaneous": [
        "Cyclamen Flash", "Copper Flash", "Bronze", "Copper Mirror", "Fuchsia", "Jade Iridium",
        "Rose Gradient Polarized", "Dark Grigio", "Alabastro", "Graphite Sfumato Cristallo",
        "Grafite Cristallo", "Cotto", "Fucsia Crystal", "Iris Sfumato Sole", "Burgundy Gradient",
        "Cordovan", "Bordeaux", "Smoke", "Ochre", "Platino", "Azure", "Lilac", "Emerald Iridium",
        "Light Azure Mirror Teal", "Transparent"
    ]
}
# ===========================================================================================================
# FRAME COLOR
lux_frame_colors = {
    'Black': [
        'Black',
        'Black Camo',
        'Black Ink',
        'Matte Black',
        'Matte Black Camo',
        'Matte Black Fade',
        'Matte Black Ink',
        'Matte Black Prizmatic',
        'Matte Black Tortoise',
        'Polished Black',
        'Black Gradient',
        'Black On Transparent',
        'Black/White',
        'Black Havana',
        'Black/Gunmetal',
        'Matte Black/Transparent Grey',
        'Gloss Black',
        'Black/Blue',
        'Black On Gold',
        'Black On Red',
        'Black On White',
        'Black/Gold',
        'Black On Silver',
        'Black On Green',
        'Black On Rose Gold',
        'Black/Silver',
        'Black/Orange',
        'Black Rubber',
        'Matte Black/Gold',
        'Amethyst'
    ],

    'Grey': [
        'Grey',
        'Grey Smoke',
        'Grey Ink',
        'Matte Grey',
        'Matte Grey Ink',
        'Matte Grey Smoke',
        'Dark Grey',
        'Grey Gradient',
        'Grey Havana',
        'Light Grey',
        'Grey On Havana',
        'Transparent Grey',
        'Grey/Silver',
        'Matte Grey Transparent',
        'Silver',
        'Dark Ink Fade',
        'Steel',
        'Satin Light Steel',
        'Satin Lead',
        'Satin Titanium',
        'Titanium'
    ],

    'Gold': [

        'Gold',
        'Gold/Black',
        'Gold/Black Matte',
        'Gold/Brown',
        'Gold/Matte Black',
        'Polished Gold',
        'Shiny Gold',
        'Antique Gold',
        'Gold Havana',
        'Gold/Silver',
        'Gold Plated',
        'Olympic Gold',
        'Rose Gold',
        'Matte Gold',
        'Light Gold',
        'Light Gold/Black',
        'Light Gold/Havana',
        'Light Gold/Bordeaux'
    ],

    'Brown': [
        'Brown',
        'Brown Tortoise',
        'Matte Brown',
        'Matte Brown Tortoise',
        'Tortoise',
        'Brown Gradient',
        'Brown Havana',
        'Havana Brown Grey',
        'Brown Mirror Gold',
        'Matte Brown Smoke',
        'Matte Brown/Pale Gold',
        'Brown/Gold',
        'Brown/Silver',
        'Bronze/Brown',
        'Brown & Grey Havana',
        'Bronze-Copper',
        'Matte Brown & Gunmetal',
        'Woodgrain',
        'Tungsten',
        'Satin Toast',
        'Sepia',
        'Polished Rootbeer',
        'Rootbeer', 'Matte New Dark Brush', 'Cordovan', 'Merlot',
        'Cognac Opal'
    ],

    'Blue': [
        'Blue',
        'Matte Blue',
        'Polished Blue',
        'Dark Blue',
        'Matte Dark Blue',
        'Matte Navy',
        'Matte Sapphire',
        'Blue Ice',
        'Sapphire',
        'Blue Havana',
        'Transparent Blue',
        'Crystal Blue',
        'Transparent Navy Blue',
        'Matte Transparent Blue',
        'Matte Artic Surf',
        'Celeste', 'Azure'
    ],

    'Red': [
        'Red',
        'Dark Red',
        'Matte Red',
        'Matte Redline',
        'Transparent Red',
        'Cherry',
        'Bordeaux',
        'Transparent Bordeaux',
        'Dark Burgundy',
        'Transparent Dark Red',
        'Red Transparent',
        'Red Aura',
        'Matte Retina Burn', 'Raspberry Glitter Transp', 'Rubedo'
    ],

    'Green': [
        'Green',
        'Dark Green',
        'Matte Green',
        'Olive',
        'Matte Olive',
        'Military Green',
        'Matte Olive Ink',
        'Matte Olive Camo',
        'Olive Ink',
        'Transparent Green',
        'Green On Black',
        'Green Transparent',
        'Olive Tortoise',
        'Jade Fade',
        'Matte Sepia', 'Opal Anise'
    ],

    'Pink': [
        'Pink',
        'Dark Pink',
        'Matte Pink',
        'Transparent Pink',
        'Crystal Pink',
        'Transparent Pastel Pink',
        'Fuchsia',
        'Milky Pink',
        'Pink Havana',
        'Powder',
        'Dark Sand',
        'Sand'
    ],

    'Violet': [

        'Violet',
        'Dark Violet',
        'Matte Violet',
        'Transparent Violet',
        'Crystal Violet',
        'Lilac',
        'Light Violet',
        'Violet Havana',
        'Matte Lilac',
        'Trans Indigo',
        'Indigo',
        'Berry', 'Fuxia Opal'
    ],

    'Yellow': [
        'Yellow',
        'Matte Yellow',
        'Tennis Ball Yellow',
        'Matte Tennis Ball Yellow',
        'Transparent Yellow',
        'Neon Yellow'
    ],

    'Miscellaneous': [
        "Havana",
        "Tortoise",
        "Crystal",
        "Transparent",
        "Smoke",
        "Gunmetal",
        "Polished Chrome",
        "Pearl",
        "Beige",
        "Ivory",
        "Bronze",
        "Copper",
        "Alabaster",
        "Carbon",
        "Graphite",
        "Metallic Green",
        "Electric Purple",
        "Terra Di Siena",
        "Tabacco Virginia",
        "Caffe",
        "Honey",
        "Miele",
        "Brushed Navy",
        "Fuxia Fluo",
        "Lead",
        "Navy",
        "Raspberry Spritzer",
        "Desert Tan",
        "Peach",
        "Vintage Check",
        "Champagne",
        "Matte Rootbeer",
        "Satin Lead",
        "Neon Orange",
        "Trans Poseidon",
        "Matte Cyan/Purple Colorshift",
        "Madreterra",
        "Cerakote Cobalt",
        "Multicam Alpine",
        "Talc",
        "Baltic Marble",
        "Striped Check",
        "Petroleum",
        "Turquoise",
        "Brushed Grenache",
        "Powder Coal",
        "Matte Midnight",
        "Matte Dark Navy",
        "Cement",
        "Matte Cement",
        "Satin Midnight",
        "Satin Corten",
        "Satin Light Berry",
        "Tartaruga Media",
        "Etruscan Marble",
        "Opal Honey",
        "Opal Rose",
        "Wisteria",
        "Plum",
        "Nude",
        "Cobalto",
        "Turtledove",
        "Matte Fog",
        "Tdf Splatter",
        "Matte Stonewash",
        "Matte Celeste",
        "Matte Desert Tan",
        "Talc/Orange",
        "Loden/Cedar",
        "Peacock/Sky",
        "Orange",
        "Polished Light Curry",
        "Matte Dark Brush",
        "Matte Forged Iron",
        "Matte Jade",
        "Sage Kotsenburg Signature",
        "Purple Haze",
        "Poseidon",
        "Ultra Purple",
        "Print Floral",
        "Satin Champagne Gradient",
        "Rubber Navy",
        "Matte Sand",
        "Dark Jade Opaline",
        "Matte Balsam",
        "Matte Terrain Tan",
        "Matte Dark Curry Opaline",
        "Light Curry",
        "Dark Amber",
        "Matte Berry",
        "Satin Jade",
        "Trans Balsam",
        "Polished Trans Jade",
        "Matte Dark Stonewash Opaline",
        "Balsam",
        "Matte Brushed Grenache",
        "Polished Trans Stonewash",
        "Polished Trans Balsam",
        "Metallic Fuxia",
        "Cordovan Metal",
        "Striped Garnet",
        "Striped Ivy",
        "Striped Tobacco",
        "Burgundy",
        "Mahogany",
        "Camel Solid",
        "Opal Taupe",
        "Dark Emerald",
        "Alumina Burgundy",
        "Alumina Petrol",
        "Opal Light Rose",
        "Opal Light Topaz",
        "Fucsia",
        "Solid Burgundy",
        "Bio Cordovan",
        "Shiny Tundra",
        "Matte Translucent Stonewash",
        "Matte Grenache",
        "Matte Stone Desert Tan",
        "Matte Ginger",
        "Matte Fern",
        "Satin Navy",
        "Polished Translucent Ginger",
        "Polished Translucent Fern",
        "Polished Oil Slick",
        "Photo Waves Azure",
        "Photo Waves Purple",
        "Dark Ruby",
        "Perla Dark Ruby",
        "Pastel Rose",
        "Nero",
        "Full Camel",
        "Camel",
        "Cream",
        "Rose",
        "Opal Cognac",
        "Opal Peach",
        "Opal Natural",
        "Opal Loden",
        "Striped Radica",
        "Abstract Orange",
        "Mogano",
        "Mint",
        "Opal Milk",
        "Metallized Orange",
        "Metallized Fern",
        "Brass",
        "Navy Solid",
        "Matte Husk",
        "Shiny Mink",
        "Shiny Husk",
        "Opal Cornelian",
        "Matte Champagne",
        "Matte Baltic",
        "Caramel",
        "Turmeric Opal",
        "Milky Primrose",
        "Coffee",
        "Coral",
        "Garnet",
        "Raspberry",
        "Fired Brick",
        "Turmenic Opal",
        "Chocolate Truffle",
        "Shiny Opaline Tundra",
        "Opaline Dark Mud",
        "Shiny Striped Purple",
        "Purple",
        "Shiny Pinot Grigio",
        "Matte Military",
        "Ash",
        "Light Iris",
        "Nutmeg Solid",
        "Chocolate Shiny",
        "Nutmeg",
        "Mulberry",
        "Bosco",
        "Check Lichen",
        "Striped Ochre",
        "Deep Kunzite",
        "Satin Grenache",
        "Moka",
        "Ruby Marble",
        "Emerald Marble",
        "Acciaio",
        "Piombo",
        "Figures Toadstool",
        "Fern Thermal",
        "Fern Dip",
        "Translucent Mist",
        "Matt Translucent Mist",
        "Matt Translucent Pacific",
        "Matt Abyss"
    ],

    'White': ['Polished Clear',
              'Matte White',
              'Polished White',
              'Satin Chrome',
              'Chrome',
              'Clear',
              'White',
              'Pewter',
              'Talc',
              'Ivory', 'Ivy Opal', 'Juta', 'Quartz', 'Trasparent', 'Polished Stonewash']}

# ======================================================================================================
# FRAME MATERIAL
luxottica_frame_material = {

    'O_Matter': ['O_Matter', 'O_matter'],
    'Plastic': [
            'Injected', 'Acetate', 'Propionate', 'Moulded Acetate',
            'Peek'
    ],
    'Horn': ['Horn'],
    'Metal': ['Metal', 'Titanium', 'Aluminium']
}

#======================================================================================================
# FRAME SHAPE
luxottica_frame_shape = {
    'Round': ['Round', 'Phantos', 'Oval'],
    'Squadre': ['Square'],
    'Rectangle': ['Rectangle'],
    'Aviator': ['Aviator', 'Pillow'],
    'Cat Eye': ['Cat Eye'],
    'Mask': ['Mask', 'Goggles', 'Goggle']

}
